export const MOCK_UNPAID_STUDENTS = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    grade: 'VII A',
    avatar: 'https://bit.ly/dan-abramov',
    amount: 50000,
  },
  {
    id: 2,
    firstName: 'Davis',
    lastName: 'Ngo',
    grade: 'VII A',
    avatar: 'https://bit.ly/dan-abramov',
    amount: 50000,
  },
  {
    id: 3,
    firstName: 'Jonathan',
    lastName: 'Tah',
    grade: 'VII A',
    avatar: 'https://bit.ly/dan-abramov',
    amount: 50000,
  },
  {
    id: 4,
    firstName: 'Edward',
    lastName: 'Johnson',
    grade: 'VII A',
    avatar: 'https://bit.ly/dan-abramov',
    amount: 50000,
  },
  {
    id: 5,
    firstName: 'William',
    lastName: 'Smith',
    grade: 'VII A',
    avatar: 'https://bit.ly/dan-abramov',
    amount: 50000,
  },
];

export const MOCK_STUDENTS = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    grade: 'VII B',
    avatar: 'https://bit.ly/dan-abramov',
    date: 'March 20, 2021',
    city: 'New York',
    phone: '123-456-7890',
    email: 'u0XbI@example.com',
    address: 'Jakarta, Indonesia',
    parentName: 'John Doe',
  },
  {
    id: 2,
    firstName: 'Davis',
    lastName: 'Ngo',
    grade: 'VII C',
    avatar: 'https://bit.ly/dan-abramov',
    date: 'March 20, 2021',
    city: 'New York',
    phone: '123-456-7890',
    email: 'u0XbI@example.com',
    address: '123 Main Street, New York, NY 10001',
    parentName: 'Davis Ngo',
  },
  {
    id: 3,
    firstName: 'Jonathan',
    lastName: 'Tah',
    grade: 'VII A',
    avatar: 'https://bit.ly/dan-abramov',
    date: 'March 20, 2021',
    city: 'New York',
    phone: '123-456-7890',
    email: 'u0XbI@example.com',
    address: '123 Main Street, New York, NY 10001',
    parentName: 'Jonathan Tah',
  },
  {
    id: 4,
    firstName: 'Edward',
    lastName: 'Johnson',
    grade: 'VII A',
    avatar: 'https://bit.ly/dan-abramov',
    date: 'March 20, 2021',
    city: 'New York',
    phone: '123-456-7890',
    email: 'u0XbI@example.com',
    address: '123 Main Street, New York, NY 10001',
    parentName: 'Edward Johnson',
  },
  {
    id: 5,
    firstName: 'William',
    lastName: 'Smith',
    grade: 'VII A',
    avatar: 'https://bit.ly/dan-abramov',
    date: 'March 20, 2021',
    city: 'New York',
    phone: '123-456-7890',
    email: 'u0XbI@example.com',
    address: '123 Main Street, New York, NY 10001',
    parentName: 'William Smith',
  },
];
