export const MOCK_TEACHERS = [
  {
    id: 1,
    documentId: '1',
    name: 'Dimitres Viga',
    firstName: 'Dimitres',
    lastName: 'Viga',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Mathematics',
    avatar: 'https://bit.ly/dan-abramov',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 2,
    name: 'Davis Ngo',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Science',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '2',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 3,
    name: 'Jonathan Tah',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Art',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '3',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 4,
    name: 'Edward Johnson',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Biology',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '4',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 5,
    name: 'Nadila Adja',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'History',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '5',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 6,
    name: 'Nadila Adja',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Physics',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '6',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 7,
    name: 'Nadila Adja',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Algorithm',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '7',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 8,
    name: 'Nadila Adja',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Engilsh',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '8',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 9,
    name: 'Nadila Adja',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Programming',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '9',
    address: 'Jakarta, Indonesia',
  },
  {
    id: 10,
    name: 'Nadila Adja',
    email: 'K5K3x@example.com',
    phone: '123-456-7890',
    subject: 'Science',
    avatar: 'https://bit.ly/dan-abramov',
    documentId: '10',
    address: 'Jakarta, Indonesia',
  },
];

export const MOCK_TEACHER_DETAIL = {
  description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
  degree: 'History Major',
  university: 'University Akademi Historia',
  startEducation: '2021',
  endEducation: '2023',
  experience: 'World History, Philosophy, Prehistoric, Culture, Ancient',
};
